// GENERATED by scripts/extract_core.mjs from the @core regions of index.html — DO NOT EDIT.
// Edit index.html, then run: node scripts/extract_core.mjs
// CI fails if this file is out of sync (scripts/check_build.mjs).

/* ---- region: limits ---- */
const MAX_TEMPLATES = 12;  // cap on saved shift templates (keeps the quick-add list scannable)
const MAX_GOALS = 12;      // cap on savings goals (bounds per-row blob growth; keeps the list scannable)

/* ---- region: dates ---- */
const todayISO = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };

/* ---- module-level date/period helpers (shared by App + the month-grid components) ---- */
const parseISODate = s => { const [y,m,d]=s.split('-').map(Number); return new Date(y,m-1,d); };
const keyOfDate = dt => `${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')}`;
/* the 14-day pay-period start (phase-aligned to `anchorISO`) that contains `dateISO` — any
   period-aligned anchor works since every period start shares the same mod-14 phase class. */
const periodStartOf = (dateISO, anchorISO) => {
  const anchor = parseISODate(anchorISO), d = parseISODate(dateISO);
  const k = Math.floor(Math.round((d - anchor)/86400000)/14);
  return keyOfDate(new Date(anchor.getFullYear(),anchor.getMonth(),anchor.getDate()+k*14));
};
/* short "Jul 13 – 26" / "Jul 27 – Aug 9" range label for a period-boundary chip */
const periodRangeLabel = (startISO) => {
  const a = parseISODate(startISO), b = new Date(a.getFullYear(),a.getMonth(),a.getDate()+13);
  const o = {month:'short',day:'numeric'};
  return a.getMonth()===b.getMonth() ? `${a.toLocaleDateString('en-US',o)} – ${b.getDate()}` : `${a.toLocaleDateString('en-US',o)} – ${b.toLocaleDateString('en-US',o)}`;
};

/* ---- region: differentials ---- */
const DIFF_DEFAULTS = {
  'base':         { name:'Day (regular)',   amount:0,    type:'dollar',     active:true,  color:'#9A9082' },
  'night':        { name:'Night',           amount:10,   type:'dollar',     active:true,  color:'#34452A' },
  'weekday-eve':  { name:'Weekday evening',  amount:3,    type:'dollar',     active:false, color:'#6E665A' },
  'weekend-day':  { name:'Weekend day',      amount:11.5, type:'dollar',     active:true,  color:'#B65D45' },
  'weekend-eve':  { name:'Weekend night',    amount:16.5, type:'dollar',     active:true,  color:'#8C4A38' },
  'holiday':      { name:'Holiday',          amount:1.5,  type:'multiplier', active:true,  color:'#D9A33C' },
  'overtime':     { name:'Overtime (1.5×)',  amount:1.5,  type:'multiplier', active:true,  color:'#11A86B' },
  'bonus-incentive':{ name:'Bonus incentive',amount:15,   type:'dollar',     active:true,  color:'#11A86B' },
};
const CUSTOM_DIFF_COLOR = '#5F6C45';
/* Shift colors are user-editable and persisted, so changing DIFF_DEFAULTS alone only reaches new
   users. A saved color moves to the new default ONLY while it still equals the pre-2026-10-03
   default for that key — anything she picked herself is left alone. Color only: never touches
   amount/type/active, so no dollar figure can move. */
const PREV_DIFF_COLORS = { 'base':'#8A93A6', 'night':'#5B4FE9', 'weekday-eve':'#8A93A6',
  'weekend-day':'#FF6B5C', 'weekend-eve':'#9B5BE9', 'holiday':'#F5A524' };
function migrateDiffColor(k, v){
  if(!v || typeof v.color!=='string') return v;
  const c = v.color.toUpperCase();
  const next = PREV_DIFF_COLORS[k] ? (c===PREV_DIFF_COLORS[k] ? DIFF_DEFAULTS[k].color : null)
             : (k.indexOf('custom-')===0 && c==='#5B4FE9' ? CUSTOM_DIFF_COLOR : null);
  return next ? {...v, color:next} : v;
}
/* ---- sample ("show me what this looks like") mode ------------------------------------
   A planner with no shifts projects $0, so a sample that shows nothing is worthless. Sample
   mode seeds one believable fortnight and tags every shift with this id, so "clear the sample"
   removes exactly what was seeded and nothing the nurse typed herself — the same contract
   patterns already use via `patternId`. Never write this id from any other path. */
const SAMPLE_PATTERN_ID = '__sample__';
/* Six 12h shifts over the fortnight from `startISO`, day-of-week deciding weekend vs night —
   the same inference the .ics import uses, so the mix reads as a real nurse's schedule
   whatever weekday the pay period happens to begin on.
   `opts` (onboarding v2, 2026-10-10) shapes the same fortnight from the funnel's answers:
   `hours` per shift, `perWeek` shifts on days 1..n of each week, and `mix` -- 'rotating' is the
   nurse mix above, 'days' makes every shift a plain day ('base'). Input only: what these shifts
   are worth is still periodPaycheck's call. Called with no opts it returns exactly what it always
   has (tests/core.test.mjs pins it), which the Healthcare equality rests on. Days 1..n keep each
   7-day chunk at or under 40 h for every hours x perWeek the funnel offers, so a seeded estimate
   carries no overtime under the 40-hour week both presets use. (Under 8/80 a 10- or 12-hour
   shift is overtime past hour 8 by definition -- that is real overtime, not a seeding artefact.) */
function buildSampleShifts(startISO, opts){
  const o = opts || {};
  const hours = (Number(o.hours) > 0 && Number(o.hours) <= 24) ? Number(o.hours) : 12;
  const perWeek = Math.max(1, Math.min(6, Math.floor(Number(o.perWeek)) || 3));
  const mix = o.mix === 'days' ? 'days' : 'rotating';
  const offs = [];
  for(let i=1;i<=perWeek;i++) offs.push(i);
  for(let i=1;i<=perWeek;i++) offs.push(7+i);
  const out = {};
  offs.forEach(off=>{
    const d = parseISODate(startISO); d.setDate(d.getDate()+off);
    const dow = d.getDay();
    const shiftType = mix==='days' ? 'base' : ((dow===0||dow===6) ? 'weekend-day' : (off%2 ? 'night' : 'base'));
    out[keyOfDate(d)] = [{ id:Date.now()+Math.random(), shiftType, hours, bonusType:'none',
                           customBonus:0, isOvertime:false, patternId:SAMPLE_PATTERN_ID }];
  });
  return out;
}

const BONUS = { none:0, charge:3, preceptor:2, oncall:5, custom:0 };
const BONUS_LABEL = { none:'None', charge:'Charge +$3/hr', preceptor:'Preceptor +$2/hr', oncall:'On-call +$5/hr', custom:'Custom (per shift)' };

/* ---- region: day-events ---- */
const EVENT_KINDS = ['pto','education','appointment','off'];
const EVENT_KIND_META = {
  pto:         { label:'PTO',        color:'#8A9A6B' },
  education:   { label:'Education',  color:'#4C6478' },
  appointment: { label:'Appt',       color:'#D9A33C' },
  off:         { label:'Off',        color:'#9A9082' },
};
const MAX_DAY_EVENTS = 4;
const MAX_NOTE_LEN = 240;
const TIME_RE = /^([01]\d|2[0-3]):[0-5]\d$/;   // "HH:MM" 24h, optional shift start

/* ---- region: ics-limits ---- */
const ICS_UID_RE = /^[A-Za-z0-9@._-]{1,128}$/;
const ICS_IMPORT_MAX_EVENTS = 200;       // hard cap per import
const ICS_IMPORT_PAST_DAYS = 60;         // import window: 60 days back...
const ICS_IMPORT_FUTURE_DAYS = 366;      // ...to 366 days forward
const ICS_IGNORED_MAX = 500;             // remembered "not a shift, hide it" uids (bounds blob growth)
const ICS_EVENT_KIND = 'appointment';    // dayEvents kind used for read-only imported calendar entries

/* ---- region: money ---- */
/* Pull the earnings rows out of a paystub's HOURS AND EARNINGS block.

   pdf.js joins a page's text items with a single space, so inside a page there are NO line
   breaks to anchor a row on. The previous version dealt with that by requiring every row to
   start "PD " or "Incentive - " — the shape of ONE employer's per-diem statement. The same
   nurse's statement two years later reads "Regular", "3rd Shift Differential", "SI2 - ...",
   so every row was skipped and the import reported "no differential rows detected".

   So: tokenise instead of pattern-matching. Words accumulate into a description until a run
   of numbers appears; that run ends the row. A row with a current rate, hours AND earnings
   carries five numbers (rate, hours, earnings, then the YTD pair) — anything shorter is a
   YTD-only line with no current activity and is skipped rather than guessed at.

   Each row is then checked against the stub's own arithmetic. Where rate x hours equals
   earnings the row is `exact` and its rate can be trusted; where it doesn't, the rate column
   is something else — Main Line Health's own footnote says it may be "from an FLSA
   calculation", which is exactly what their overtime row is. Those are returned but flagged,
   never silently treated as an hourly rate. */
const EARN_NUM_RE = /^[\d,]+\.\d{2,6}$/;
const EARN_CENT_TOLERANCE = 0.02;   // stubs round per line; 65.15 x 30 prints as 1,954.51
function parseEarningsRows(sectionText){
  /* Drop the column header (and the dashed Current/YTD rule above it) so "Description Rate
     Hours Earnings" cannot land in the first row's description. */
  const body = String(sectionText||'')
    .replace(/^[\s\S]*?Description\s+Rate\s+Hours\s+Earnings(?:\s+Hours\s+Earnings)?/i, '');
  const toks = body.split(/\s+/).filter(Boolean);
  const out = [], seen = new Set();
  let words = [], i = 0;
  const numOf = t => parseFloat(t.replace(/,/g,''));
  while(i < toks.length){
    if(!EARN_NUM_RE.test(toks[i])){ words.push(toks[i++]); continue; }
    const nums = [];
    while(i < toks.length && EARN_NUM_RE.test(toks[i])) nums.push(numOf(toks[i++]));
    const description = words.join(' ').trim(); words = [];
    if(!description || nums.length < 5) continue;          // YTD-only line: no current activity
    const [rate, hours, earnings] = nums;
    if(!(rate > 0) || !(hours > 0) || !(hours < 200)) continue;
    const key = description.toLowerCase();
    if(seen.has(key)) continue;
    seen.add(key);
    out.push({ description, rate, hours, earnings,
      exact: Math.abs(rate*hours - earnings) <= EARN_CENT_TOLERANCE });
  }
  return out;
}

/* Turn parsed earnings rows into the differential amounts this app would write.

   This is the whole reason the importer exists, so it lives in one function that both the
   review sheet and the apply step call — a sheet that previews one number while apply writes
   another is worse than no preview.

   A paystub's Rate column does not always mean the same thing, and the description does not
   reliably say which. Two shapes, on the same nurse's stubs two years apart:

     PD Weekday Eve           69.790000    full hourly rate, differential already inside it
     3rd Shift Differential    7.000000    the differential alone; base pay is on its own row

   Subtracting base from the second yields -$63.81/hr. Arithmetic tells them apart without
   trusting the wording: a full rate is at least the base rate, a bare differential is below it.
   Either way the result can never be negative.

   Rows the stub's own arithmetic does not support are skipped outright. On the 2023 stub that
   is "PD Weekend Overtime Eve 67.034424", whose Rate column is a blended FLSA figure rather
   than an hourly rate — and which classifies as weekend-eve and sits BELOW the real weekend
   row, so it was silently overwriting a $4.64 weekend differential with $1.88.

   Multiplier differentials (holiday, overtime) are absent from the result on purpose: their
   amount is a ratio we do not read off a stub. Callers activate those keys without touching
   the amount. */
function differentialsFromStub(rows, baseRate, defaults){
  const b = Number(baseRate)||0, defs = defaults || DIFF_DEFAULTS, out = {};
  if(!(b > 0)) return out;
  (rows||[]).forEach(r => {
    if(r && r.exact === false) return;
    const key = classifyPaystubRow(r && r.description);
    if(!key || key === 'base') return;
    if((defs[key]||{}).type === 'multiplier') return;
    const rate = Number(r.rate)||0;
    if(!(rate > 0)) return;
    out[key] = Math.round((rate >= b ? rate - b : rate) * 100)/100;
  });
  return out;
}

/* Map a parsed paystub earnings-row description to a differential key.
   Weekend variants are tested first so "Weekend Night" -> weekend-eve (not night).
   Returns null for rows we can't confidently classify — callers MUST skip those
   and never fall back to 'base' (that would corrupt the Day-regular rate).

   Matching is on whole words. Substring matching read "SI2 - Staffing Incentive Level" as an
   evening differential, because "Level" contains "eve" — a staffing incentive would have
   silently become her evening rate.

   Shift NUMBERS are recognised too: employers who schedule 12-hour shifts often still name
   differentials by the 8-hour shift they came from, so "3rd Shift Differential" is the night
   rate and "2nd Shift Differential" is the evening one. The deny-list ahead of them keeps
   rows that merely mention a paid category — downstaffing drawn from a holiday bank, unpaid
   absence, leave, bonuses, awards — from being read as a differential. */
const PAYSTUB_NOT_A_DIFFERENTIAL = ['downstaff','unpaid','absence','leave','bonus','award',
  'retro','disab','pension','inservice','seminar','seminars','reimbursement','stipend'];
function classifyPaystubRow(desc){
  const words = String(desc||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().split(' ');
  const d = ' ' + words.join(' ') + ' ';
  const has = w => d.indexOf(' '+w+' ') >= 0;
  const anyOf = (...ws) => ws.some(has);
  if(PAYSTUB_NOT_A_DIFFERENTIAL.some(has)) return null;
  if(has('weekend') && anyOf('eve','evening','night','nights')) return 'weekend-eve';
  if(has('weekend') && has('day')) return 'weekend-day';
  if(has('weekday') && anyOf('eve','evening')) return 'weekday-eve';
  if(anyOf('3rd','third') && has('shift')) return 'night';
  if(anyOf('2nd','second') && has('shift')) return 'weekday-eve';
  if(anyOf('night','nights')) return 'night';
  if(anyOf('eve','evening')) return 'weekday-eve';
  if(has('overtime')) return 'overtime';
  if(has('holiday')) return 'holiday';
  return null;
}

/* Validate/coerce an untrusted data blob (from cloud, localStorage, or imported JSON)
   into safe shapes before it ever reaches React state. A malformed blob must never crash
   calc()'s (arr||[]).forEach nor silently corrupt every calculation with string/NaN fields.
   Returns null for a non-object; otherwise only keys that passed validation are present, so
   applyData falls back to the current default for anything omitted. */
function sanitizeData(d){
  if(!d || typeof d!=='object' || Array.isArray(d)) return null;
  const out = {};
  const setNum = (key,v)=>{ const n=Number(v); if(isFinite(n)) out[key]=n; };
  if(typeof d.name==='string') out.name = d.name;
  if(d.baseRate!=null) setNum('baseRate', d.baseRate);
  if(d.federalTaxRate!=null) setNum('federalTaxRate', d.federalTaxRate);
  if(d.stateTaxRate!=null) setNum('stateTaxRate', d.stateTaxRate);
  if(d.pretaxDeductions!=null) setNum('pretaxDeductions', d.pretaxDeductions);
  if(d.posttaxDeductions!=null) setNum('posttaxDeductions', d.posttaxDeductions);
  /* Whitelisted like estimateMode and workPeriod two lines down. computeNet only knows
     'standard' and 'percent'; any other string fell through to fica = 0, overstating take-home
     by ~7.65% of gross with nothing shown to say so (~$184 on a $2,400 period). The <select>
     cannot produce a third value, so this only bites a corrupt or hand-edited blob — which is
     exactly what this function exists for (council #4 / code-quality-01). */
  if(d.ficaWithholdingType==='standard' || d.ficaWithholdingType==='percent') out.ficaWithholdingType = d.ficaWithholdingType;
  if(d.ficaWithholdingPercent!=null) setNum('ficaWithholdingPercent', d.ficaWithholdingPercent);
  if(typeof d.payPeriodStart==='string') out.payPeriodStart = d.payPeriodStart;
  /* Employer pay policy. Whitelisted like estimateMode, so a corrupt or hostile blob can only
     ever land on the safe default ('40' + the FLSA regular rate) rather than silently switching
     a nurse onto an 8/80 schedule and inventing overtime she is not owed. */
  if(WORK_PERIODS.indexOf(d.workPeriod)>=0) out.workPeriod = d.workPeriod;
  if(OT_METHODS.indexOf(d.otMethod)>=0) out.otMethod = d.otMethod;
  if(d.mealBreakMins!=null){ const mm=Number(d.mealBreakMins); if(isFinite(mm)&&mm>=0&&mm<=120) out.mealBreakMins = mm; }
  if(MEAL_MODES.indexOf(d.mealBreakMode)>=0) out.mealBreakMode = d.mealBreakMode;
  /* estimateMode: '' (fully set up, or the banner was dismissed) | 'rough' (their own base rate,
     default differentials + taxes) | 'sample' (nothing of theirs entered yet). Whitelisted, so a
     corrupt or hostile blob can only ever land on '' — i.e. no banner, never a false one. */
  if(d.estimateMode==='rough' || d.estimateMode==='sample') out.estimateMode = d.estimateMode;
  /* Onboarding v2's three answers (2026-10-10). Not pay inputs -- a persona picks starting values
     and cards, never a rule -- but whitelisted the same way: anything else is dropped, never
     coerced, so a corrupt blob reads as "never answered" rather than as somebody's profession. */
  if(PERSONA_IDS.indexOf(d.persona)>=0) out.persona = d.persona;
  if(WORK_STATUSES.indexOf(d.workStatus)>=0) out.workStatus = d.workStatus;
  if(UNION_ANSWERS.indexOf(d.union)>=0) out.union = d.union;
  // shifts: object of date-key -> array of shift objects; keep only well-formed entries.
  if(d.shifts && typeof d.shifts==='object' && !Array.isArray(d.shifts)){
    const s = {};
    Object.entries(d.shifts).forEach(([k,v])=>{
      if(!Array.isArray(v)) return;
      const clean = v.filter(x=> x && typeof x==='object'
          && typeof x.shiftType==='string'
          && isFinite(Number(x.hours)) && Number(x.hours)>0 && Number(x.hours)<=24)
        .map(x=>{
          const o = {...x, hours:Number(x.hours), isOvertime:x.isOvertime===true};
          /* Omitted rather than stored false: this rides on every shift in the blob, which is
             capped at MAX_BLOB_BYTES, and the overwhelming majority of shifts did get a lunch. */
          if(x.noMeal===true) o.noMeal = true; else delete o.noMeal;
          if(typeof o.start!=='string' || !TIME_RE.test(o.start)) delete o.start;
          if(typeof o.icsUid!=='string' || !ICS_UID_RE.test(o.icsUid)) delete o.icsUid;
          return o;
        });
      if(clean.length) s[k] = clean;
    });
    out.shifts = s;
  }
  // dayEvents: date-key -> up to MAX_DAY_EVENTS {id,kind,hours?}; one entry per kind per day.
  if(d.dayEvents && typeof d.dayEvents==='object' && !Array.isArray(d.dayEvents)){
    const de = {};
    Object.entries(d.dayEvents).forEach(([k,v])=>{
      if(!Array.isArray(v)) return;
      const seenKinds = new Set();
      const clean = [];
      v.forEach(x=>{
        if(!x || typeof x!=='object' || typeof x.kind!=='string' || EVENT_KINDS.indexOf(x.kind)<0) return;
        if(seenKinds.has(x.kind)) return;   // dedupe: only one event per kind per day
        seenKinds.add(x.kind);
        const ev = { id:(typeof x.id==='string'||typeof x.id==='number')?x.id:(Date.now()+Math.random()), kind:x.kind };
        if(x.hours!=null){ const n=Number(x.hours); if(isFinite(n) && n>=0 && n<=24) ev.hours = n; }
        // Imported calendar entries carry their source uid so the next sync recognises them
        // instead of re-asking. Same validation as shifts' icsUid.
        if(typeof x.icsUid==='string' && ICS_UID_RE.test(x.icsUid)) ev.icsUid = x.icsUid;
        clean.push(ev);
      });
      if(clean.length) de[k] = clean.slice(0,MAX_DAY_EVENTS);
    });
    out.dayEvents = de;
  }
  /* icsIgnored: { icsUid: true } — calendar entries the user dismissed as "not a shift, hide it".
     Remembered so a silent app-open sync never re-opens the questionnaire for the same personal
     event again. Bounded so a huge shared calendar can't grow the blob past MAX_BLOB_BYTES. */
  if(d.icsIgnored && typeof d.icsIgnored==='object' && !Array.isArray(d.icsIgnored)){
    const ig = {};
    Object.keys(d.icsIgnored).slice(0, ICS_IGNORED_MAX).forEach(u=>{
      if(typeof u==='string' && ICS_UID_RE.test(u) && d.icsIgnored[u]) ig[u] = true;
    });
    out.icsIgnored = ig;
  }
  // notes: date-key -> short free-text string, trimmed and capped.
  if(d.notes && typeof d.notes==='object' && !Array.isArray(d.notes)){
    const nt = {};
    Object.entries(d.notes).forEach(([k,v])=>{
      if(typeof v!=='string') return;
      const trimmed = v.trim().slice(0,MAX_NOTE_LEN);
      if(trimmed) nt[k] = trimmed;
    });
    out.notes = nt;
  }
  // customWithholdings: array of {name:string, amount coercible, type:'percent'|'dollar'}.
  if(Array.isArray(d.customWithholdings)){
    out.customWithholdings = d.customWithholdings.filter(w=> w && typeof w==='object'
        && typeof w.name==='string'
        && isFinite(Number(w.amount))
        && (w.type==='percent' || w.type==='dollar'))
      .map(w=>({name:w.name, amount:Number(w.amount), type:w.type}));
  }
  // differentials: coerce each entry so `amount` is finite and `type` is valid — a non-numeric
  // amount or bad type would flow into hourlyRate() and yield NaN take-home. Preserve
  // name/color/active (needed for custom-* keys with no DIFF_DEFAULTS); applyData merges over defaults.
  if(d.differentials && typeof d.differentials==='object' && !Array.isArray(d.differentials)){
    const dd = {};
    Object.entries(d.differentials).forEach(([k,v])=>{
      if(!v || typeof v!=='object' || Array.isArray(v)) return;
      const type = (v.type==='dollar'||v.type==='multiplier'||v.type==='percent') ? v.type : 'dollar';
      const amt = Number(v.amount);
      /* A multiplier is a coefficient, so the safe fallback is 1 (pay the base rate), not 0 —
         0 prices the shift at $0. NumInput commits its `min` on a select-all-then-tap-away, so
         a blanked Holiday field used to persist 0x and show ~$0 for a Christmas shift forever,
         with nothing to repair it (council #3 / wage-math-01). Dollar/percent keep 0, where
         "no differential" is the correct reading of an empty box. */
      const safe = type==='multiplier'
        ? (isFinite(amt) && amt > 0 ? amt : 1)
        : (isFinite(amt) ? amt : 0);
      dd[k] = {...v, amount: safe, type};
    });
    out.differentials = dd;
  }
  // templates: repeating-shift presets. Cap MAX_TEMPLATES, validate shape, drop malformed entries.
  if(Array.isArray(d.templates)){
    out.templates = d.templates.filter(t=> t && typeof t==='object'
        && typeof t.name==='string' && t.name.length>0 && t.name.length<=40
        && typeof t.shiftType==='string'
        && isFinite(Number(t.hours)) && Number(t.hours)>=0.1 && Number(t.hours)<=24
        && typeof t.bonusType==='string')
      .slice(0,MAX_TEMPLATES)
      .map(t=>({
        id: (typeof t.id==='string'||typeof t.id==='number') ? t.id : (Date.now()+Math.random()),
        name: t.name,
        shiftType: t.shiftType,
        hours: Number(t.hours),
        bonusType: t.bonusType,
        customBonus: isFinite(Number(t.customBonus)) ? Number(t.customBonus) : 0,
        isOvertime: t.isOvertime===true,   // council 2026-09-13 (#9): templates used to drop the OT flag silently
        ...(typeof t.start==='string' && TIME_RE.test(t.start) ? {start:t.start} : {})
      }));
  }
  // goals: savings targets — array of {id, name:string(1..40), target:number>0}. Capped at MAX_GOALS.
  // target is coerced to a finite positive number so a malformed value can't yield NaN percentages
  // in the shift preview (same defensive coercion as differentials/templates).
  if(Array.isArray(d.goals)){
    out.goals = d.goals.filter(g=> g && typeof g==='object'
        && typeof g.name==='string' && g.name.trim().length>0 && g.name.length<=80
        && isFinite(Number(g.target)) && Number(g.target)>0)
      .slice(0,MAX_GOALS)
      .map(g=>({
        id: (typeof g.id==='string'||typeof g.id==='number') ? g.id : (Date.now()+Math.random()),
        name: g.name.trim().slice(0,40),
        target: Number(g.target),
      }));
  }
  // patterns: saved rotations — [{id, name:string(1..40), anchor:'YYYY-MM-DD', cells:[cell|null]}],
  // capped at MAX_PATTERNS. Each cell is re-validated (kind, hours 0.1..24, optional start/bonus)
  // so a malformed cell can't reach shiftGross() as NaN hours or an unknown bonus type.
  if(Array.isArray(d.patterns)){
    const bonusKeys = Object.keys(BONUS_LABEL);
    const validISO = s => typeof s==='string' && /^\d{4}-\d{2}-\d{2}$/.test(s) && keyOfDate(parseISODate(s))===s;
    out.patterns = d.patterns.filter(p=> p && typeof p==='object'
        && typeof p.name==='string' && p.name.trim().length>0
        && validISO(p.anchor)
        && Array.isArray(p.cells) && p.cells.length>=PATTERN_MIN_CYCLE && p.cells.length<=PATTERN_MAX_CYCLE)
      .slice(0,MAX_PATTERNS)
      .map(p=>({
        id: (typeof p.id==='string'||typeof p.id==='number') ? p.id : (Date.now()+Math.random()),
        name: p.name.trim().slice(0,40),
        anchor: p.anchor,
        cells: p.cells.map(c=>{
          if(!c || typeof c!=='object' || PATTERN_KINDS.indexOf(c.kind)<0) return null;
          const h = Number(c.hours);
          if(!isFinite(h) || h<0.1 || h>24) return null;
          if(c.kind==='fixed' && typeof c.shiftType!=='string') return null;
          const o = {kind:c.kind, hours:h};
          if(c.kind==='fixed') o.shiftType = c.shiftType;
          if(typeof c.start==='string' && TIME_RE.test(c.start)) o.start = c.start;
          if(typeof c.bonusType==='string' && bonusKeys.indexOf(c.bonusType)>=0 && c.bonusType!=='none') o.bonusType = c.bonusType;
          if(o.bonusType==='custom'){ const cb=Number(c.customBonus); o.customBonus = isFinite(cb)?cb:0; }
          if(c.isOvertime===true) o.isOvertime = true;
          return o;
        }),
      }));
  }
  if('setupComplete' in d) out.setupComplete = d.setupComplete;
  /* jobs + the jobId stamp. Runs last so a migrated job can carry the already-sanitized rate
     and differentials, and so every shift above has been validated before it is stamped. */
  if(Array.isArray(d.jobs) && d.jobs.length){
    const seen = {};
    out.jobs = d.jobs.slice(0, MAX_JOBS).map(makeJob)
      .filter(j=>{ if(!j.id || seen[j.id]) return false; seen[j.id]=true; return true; });
  }
  if(!out.jobs || !out.jobs.length){
    /* A pre-jobs blob: everything she has ever logged belongs to one implicit employer. The
       rate and differentials move onto it verbatim, so no historical shift reprices. This is
       the bug the job record fixes today, before any second employer exists — one global
       baseRate means changing status (per diem -> staff) silently repriced every past shift. */
    out.jobs = [makeJob({ id: DEFAULT_JOB_ID, baseRate: out.baseRate,
      differentials: out.differentials || null,
      workPeriod: out.workPeriod, otMethod: out.otMethod,
      mealBreakMins: out.mealBreakMins, mealBreakMode: out.mealBreakMode })];
  }
  if(out.shifts){
    const known = {}; out.jobs.forEach(j=>{ known[j.id]=true; });
    const fallbackId = out.jobs[0].id;
    Object.keys(out.shifts).forEach(k=>{
      out.shifts[k] = out.shifts[k].map(x=>
        (typeof x.jobId==='string' && known[x.jobId]) ? x : {...x, jobId: fallbackId});
    });
  }
  return out;
}

const fmt = n => '$' + Number(n||0).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:0});
const fmt2 = n => '$' + Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});

/* ---------- money: integer cents ------------------------------------------------------
   A float cannot hold a cent. 70.81 * 47.10 is 3335.1509999999994, and once figures like that
   accumulate across a pay period the total drifts away from the paycheck it is meant to predict.
   Every computation in the wage core runs on integer cents. The dollar-taking/returning wrappers
   below (hourlyRate, shiftGross, computeNet) exist so that call sites which still speak dollars
   keep working byte-identically while the cents layer is pushed outward commit by commit.

   Rates stay FRACTIONAL cents on purpose — a real regular rate is $67.034424/hr (Main Line
   Health, 2023-09-30 stub) — and rounding happens once, at the earnings line, exactly where a
   payroll system rounds it. */
const toCents   = d => Math.round((Number(d)||0) * 100);
const fromCents = c => c / 100;
/* Commercial rounding: half away from zero. Matches the printed earnings lines on every real
   stub checked — 69.79 x 12.50h prints as 872.38, not 872.37. Math.round alone rounds -0.5
   toward +Infinity, which would silently favour one direction on negative adjustments. */
const roundCents = x => (x < 0 ? -Math.round(-x) : Math.round(x));

/* ---------- jobs -----------------------------------------------------------------------
   One nurse, N employment relationships. This is a data spine, not a feature: until a second
   job is created nothing about the UI changes. It exists now because `user_data` is a single
   un-versioned blob that sanitizeData must validate forever, so adding keys is cheap today and
   a migration later.

   What lives on a job is what an EMPLOYER decides: the rate, the differentials, the work
   period, how overtime is computed, how often it pays. What does NOT live here is tax — that
   follows the nurse's residence and the state she works in, both of which change independently
   of the employer (one travel contract can span several states), so tax stays user-level.
   Don't "tidy" it onto the job. */
const DEFAULT_JOB_ID = 'job-1';
const MAX_JOBS = 8;
/* '40' = the FLSA 40-hour workweek. '8-80' = the section 7(j) hospital election: overtime past
   8 in a day AND 80 in a 14-day period, whichever is crossed. Read by the overtime derivation,
   which lands in the next commit; stored here so one migration covers both. */
const WORK_PERIODS = ['40','8-80'];
/* 'regular-rate' = FLSA 778.115: total straight-time remuneration / total hours, premium at 0.5x
   on the overtime hours. 'base-plus-diff' = the common (and often incorrect) shortcut of
   1.5 x base with the differential added flat. Which one an employer uses is observable from a
   paystub and is not ours to assume. */
const OT_METHODS = ['regular-rate','base-plus-diff'];
const PAY_FREQUENCIES = ['weekly','biweekly','semimonthly'];
/* How an employer handles the unpaid meal break.
   'included'  — the hours she logs are ALREADY net of it. Main Line Health schedules a
                 12.5-hour block, deducts 30 minutes and pays 12.0, so the "12 hours" she
                 types is the paid figure and nothing needs subtracting. Submitting
                 "received no lunch" pays the full block, which is an ADD-BACK.
   'deducted'  — she logs the scheduled block and the employer subtracts the meal. This is
                 the arrangement behind most healthcare meal-break litigation (auto-deduct
                 with an opt-out gated behind the very condition that creates it).
   Only 'included' is proven against a real stub, so it is the default and the other is a
   setting — this varies by employer and guessing it wrong silently moves every shift. */
const MEAL_MODES = ['included','deducted'];
const DEFAULT_MEAL_MINS = 30;

function makeJob(o){
  const j = o && typeof o==='object' ? o : {};
  const rate = Number(j.baseRate);
  return {
    id: (typeof j.id==='string' && j.id) ? j.id : DEFAULT_JOB_ID,
    name: typeof j.name==='string' ? j.name.trim().slice(0,40) : '',
    baseRate: isFinite(rate) ? rate : 0,
    differentials: (j.differentials && typeof j.differentials==='object' && !Array.isArray(j.differentials))
      ? j.differentials : null,
    workPeriod: WORK_PERIODS.indexOf(j.workPeriod)>=0 ? j.workPeriod : '40',
    otMethod: OT_METHODS.indexOf(j.otMethod)>=0 ? j.otMethod : 'regular-rate',
    payFrequency: PAY_FREQUENCIES.indexOf(j.payFrequency)>=0 ? j.payFrequency : 'biweekly',
    mealBreakMins: (()=>{ const m=Number(j.mealBreakMins); return (isFinite(m)&&m>=0&&m<=120)?m:DEFAULT_MEAL_MINS; })(),
    mealBreakMode: MEAL_MODES.indexOf(j.mealBreakMode)>=0 ? j.mealBreakMode : 'included',
    active: j.active !== false,
  };
}
/* jobs as a map for lookup by id; the blob stores an array so ordering survives a round trip. */
const jobMap = list => { const m={}; (list||[]).forEach(j=>{ if(j && j.id) m[j.id]=j; }); return m; };

/* ---------- overtime ------------------------------------------------------------------
   Overtime is a property of a WORK PERIOD, not of a shift. Until now it was a checkbox the
   nurse ticked per shift, which meant a 48-hour week with nothing ticked projected zero
   overtime — the single largest thing the engine could not see.

   This returns a PREMIUM that is added on top of the straight-time gross the shifts already
   produce. That shape is deliberate: shiftGross keeps paying every logged hour at its own
   rate, and 29 CFR 778.115 is satisfied by adding half the regular rate on the hours past the
   threshold. It is also how Main Line Health's own stubs are laid out — straight time on
   every line, then a separate overtime line whose rate the payroll system footnotes as
   "from an FLSA calculation".

   A shift the nurse flagged by hand is already paid 1.5x inside shiftGross. Its hours are
   subtracted from the derived overtime rather than charged again, so turning this on cannot
   silently double anybody's existing figure. */

/* Straight-time cents for a shift: what it earns before any overtime premium. */
const straightTimeCents = (baseCents, diff, s, meal) =>
  shiftGrossCents(baseCents, diff, {...s, isOvertime:false}, meal);

/* Split date keys into the job's work periods. A 40-hour workweek is seven consecutive days
   from the first key — biweekly pay periods here start on a Sunday, the same day MLH's do, so
   the chunks line up with the employer's workweek. An 8/80 election is ONE fourteen-day
   period, not two weeks, because its second threshold is 80 hours across the whole thing. */
function workPeriodChunks(job, dateKeys){
  const keys = (dateKeys||[]).slice().sort();
  if(job && job.workPeriod==='8-80') return keys.length ? [keys] : [];
  const out = [];
  for(let i=0;i<keys.length;i+=7) out.push(keys.slice(i,i+7));
  return out;
}

function overtimePremiumCents(job, shifts, dateKeys){
  const baseCents = toCents(job && job.baseRate);
  const diffs = (job && job.differentials) || {};
  const method = (job && job.otMethod) || 'regular-rate';
  const is880 = !!(job && job.workPeriod==='8-80');
  const out = { otHours:0, premiumCents:0, flaggedHours:0, periods:[] };

  workPeriodChunks(job, dateKeys).forEach(keys=>{
    let hours=0, stCents=0, flaggedHours=0, dailyExcess=0;
    keys.forEach(k=>{
      let dayHours = 0;
      ((shifts||{})[k]||[]).forEach(s=>{
        if(job && job.id && typeof s.jobId==='string' && s.jobId!==job.id) return;
        /* Paid hours, not logged hours: a missed lunch is half an hour of real work and
           counts toward the overtime threshold like any other. */
        const h = paidHoursOf(s, job);
        hours += h; dayHours += h;
        stCents += straightTimeCents(baseCents, diffs[s.shiftType], s, job);
        if(s.isOvertime===true) flaggedHours += h;
      });
      if(dayHours > 8) dailyExcess += dayHours - 8;
    });
    if(!hours) return;
    /* The regular rate: total straight-time remuneration divided by total hours worked.
       Per-hour and flat bonuses are inside stCents on purpose — a non-discretionary bonus
       belongs in the regular rate (DOL Fact Sheet #54), and leaving charge or preceptor pay
       out is exactly how the common shortcut under-reports overtime. */
    const regularRateCents = stCents / hours;
    /* 8/80 carries two thresholds. An hour cannot be overtime twice, so take whichever
       computation is larger rather than summing them — the reading that pays the higher of
       the daily and period results. Employers differ here; the 40-hour default does not. */
    const otHours = is880
      ? Math.max(dailyExcess, Math.max(0, hours - 80))
      : Math.max(0, hours - 40);
    const unflagged = Math.max(0, otHours - flaggedHours);
    const premiumBase = method==='base-plus-diff' ? baseCents : regularRateCents;
    const premiumCents = roundCents(0.5 * premiumBase * unflagged);
    out.otHours += unflagged;
    out.flaggedHours += flaggedHours;
    out.premiumCents += premiumCents;
    out.periods.push({ hours, otHours:unflagged, flaggedHours, regularRateCents, premiumCents });
  });
  return out;
}

/* Hours, shift count and gross PER JOB across a set of date keys.
   The grouping is the entire point. An FLSA workweek belongs to one employer, so hours worked
   for two employers must never land in a single overtime computation — unrelated employers do
   not aggregate, and a nurse holding a staff line plus a marketplace account has two separate
   40-hour weeks, not one 80-hour one. Today there is exactly one group; the discipline has to
   exist before the second job does, or the first two-job user silently gets phantom overtime. */
function groupHoursByJob(jobs, shifts, dateKeys, dayEvents){
  const out = {};
  const bucket = id => (out[id] = out[id] || { hours:0, shifts:0, grossCents:0, ptoHours:0 });
  (dateKeys||[]).forEach(k=>{
    ((shifts||{})[k]||[]).forEach(s=>{
      const id = (typeof s.jobId==='string' && s.jobId) ? s.jobId : DEFAULT_JOB_ID;
      const job = (jobs||{})[id];
      const b = bucket(id);
      b.hours += paidHoursOf(s, job);
      b.shifts++;
      if(job) b.grossCents += shiftGrossCents(toCents(job.baseRate), (job.differentials||{})[s.shiftType], s, job);
    });
    /* PTO is paid by a specific employer too, but a day event carries no job today, so it lands
       on the default job — the same job every pre-migration shift landed on. */
    ((dayEvents||{})[k]||[]).forEach(e=>{
      if(e.kind!=='pto' || !(e.hours>0)) return;
      const id = (typeof e.jobId==='string' && e.jobId) ? e.jobId : DEFAULT_JOB_ID;
      const job = (jobs||{})[id];
      const b = bucket(id);
      b.ptoHours += Number(e.hours)||0;
      b.hours += Number(e.hours)||0;
      if(job) b.grossCents += roundCents(toCents(job.baseRate) * (Number(e.hours)||0));
    });
  });
  return out;
}

/* Hours this shift is PAID for, which is not always the hours she logged. `meal` is a job
   (or anything carrying mealBreakMins/mealBreakMode); omit it and the logged hours are used
   verbatim, which is what every pre-existing call site does. */
function paidHoursOf(s, meal){
  const h = Number(s && s.hours)||0;
  if(!meal) return h;
  const mins = Number(meal.mealBreakMins);
  const m = (isFinite(mins) && mins>0) ? mins/60 : 0;
  if(!m) return h;
  if(meal.mealBreakMode==='deducted') return Math.max(0, s.noMeal===true ? h : h - m);
  return s.noMeal===true ? h + m : h;
}

/* The differential-inclusive hourly rate, in (possibly fractional) cents. */
function hourlyRateCents(baseCents, diff){
  if(!diff) return baseCents;
  const amt = Number(diff.amount)||0;
  if(diff.type==='multiplier') return baseCents * amt;
  if(diff.type==='percent') return baseCents * (1 + amt/100);
  return baseCents + toCents(amt);
}
/* One shift's gross, in whole cents. Each component rounds on its own line the way a payroll
   system prints it (rate x hours is one line, a per-hour bonus is another), then the lines are
   summed as integers so a period total cannot accumulate float dust. */
function shiftGrossCents(baseCents, diff, s, meal){
  const hours = paidHoursOf(s, meal);
  const perHrCents = s.bonusType==='custom' ? 0 : toCents(BONUS[s.bonusType]||0);
  const flatCents  = s.bonusType==='custom' ? toCents(parseFloat(s.customBonus)||0) : 0;
  // Overtime stacks ON TOP of the shift differential: the differential-inclusive hourly rate
  // is paid at 1.5× (per-hour/flat bonuses stay at face value, matching the legacy 'overtime'
  // shift-type which only multiplied the hourly rate). isOvertime is an independent flag, so a
  // night OT shift earns 1.5×(base+night diff) instead of losing the differential to a flat 1.5×base.
  const otMult = s.isOvertime ? 1.5 : 1;
  return roundCents(hourlyRateCents(baseCents, diff) * otMult * hours)
       + roundCents(perHrCents * hours)
       + flatCents;
}
/* Dollar-in/dollar-out wrappers. Every existing call site reads these and is unchanged. */
function hourlyRate(base, diff){ return fromCents(hourlyRateCents(toCents(base), diff)); }
function shiftGross(base, diff, s, meal){ return fromCents(shiftGrossCents(toCents(base), diff, s, meal)); }


/* ---------- Pattern lab: repeating rotations ----------
   A pattern is a cycle of N days (7 / 8 / 14 / 28…) where each cell is either off (null) or a
   shift brush {kind:'day'|'night'|'fixed', hours, start?, shiftType?, bonusType?, customBonus?}.
   Generic 'day'/'night' cells resolve to the weekend differential when they land on a Sat/Sun
   (the same inference the .ics import uses); 'fixed' cells (built from a template) keep their
   shiftType. Everything in this section is pure so the harness can test it against the wage core. */
const MAX_PATTERNS = 8;
const PATTERN_MIN_CYCLE = 2, PATTERN_MAX_CYCLE = 42;
const PATTERN_KINDS = ['day','night','fixed'];
const PATTERN_CYCLE_CHOICES = [7,8,14,28];
const PATTERN_APPLY_WEEKS = [4,6,8,12];
const DOW_SHORT = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const gcd = (a,b)=>{ a=Math.abs(a); b=Math.abs(b); while(b){ const t=a%b; a=b; b=t; } return a||1; };
const lcm = (a,b)=> a*b/gcd(a,b);

/* Rotations nurses actually describe. `cells` is written by weekday from Sunday (a 14-day preset
   is two Sunday-start weeks) and rotated onto the anchor date's weekday when picked; a
   `byDow:false` preset (4 on / 4 off) has no weekday meaning and is used as-is.
   D = 12h day starting 07:00, N = 12h night starting 19:00, _ = off. */
const PATTERN_PRESETS = [
  { id:'mtw-nights', name:'Mon–Wed nights', cycle:7, byDow:true, cells:'_NNN___',
    blurb:'Three 12s back to back, the same days every week.' },
  { id:'3-1-3-7', name:'3 on, 1 off, 3 on, 7 off', cycle:14, byDow:true, cells:'_____DD'+'D_DDD__',
    blurb:'Every other weekend worked, then a whole week off.' },
  { id:'pitman', name:'2-2-3 (Pitman)', cycle:14, byDow:true, cells:'_DD__DD'+'D__DD__',
    blurb:'Never more than 3 in a row; every other weekend is a 3-day one.' },
  { id:'4on4off', name:'4 on, 4 off nights', cycle:8, byDow:false, cells:'NNNN____',
    blurb:'Long breaks — but the days drift across the week.' },
  { id:'weekend', name:'Weekend program (Fri–Sun)', cycle:7, byDow:true, cells:'D____DD',
    blurb:'Weekdays free, priced with your weekend differentials.' },
];
const PATTERN_BRUSHES = [
  { key:'day12',   kind:'day',   hours:12, start:'07:00', label:'Day' },
  { key:'night12', kind:'night', hours:12, start:'19:00', label:'Night' },
  { key:'day8',    kind:'day',   hours:8,  start:'07:00', label:'Day' },
  { key:'night8',  kind:'night', hours:8,  start:'23:00', label:'Night' },
];
function presetCell(ch){
  if(ch==='D') return {kind:'day', hours:12, start:'07:00'};
  if(ch==='N') return {kind:'night', hours:12, start:'19:00'};
  return null;
}
/* Instantiate a preset anchored on `anchorISO`: cell i lands on anchor+i, whose weekday is
   (anchorDow+i)%7, so a by-weekday preset is read at (anchorDow+i) % cycle. */
function patternFromPreset(preset, anchorISO){
  const w = parseISODate(anchorISO).getDay();
  const cells = Array.from({length:preset.cycle},(_,i)=> presetCell(preset.cells[preset.byDow ? (w+i)%preset.cycle : i]));
  return { id:Date.now()+Math.random(), name:preset.name, anchor:anchorISO, cells };
}
function blankPattern(anchorISO, cycle){
  return { id:Date.now()+Math.random(), name:'', anchor:anchorISO, cells:Array.from({length:cycle||7},()=>null) };
}
/* Two cells paint the same thing (re-painting a cell with its own brush clears it). */
function patternCellEq(a,b){
  if(!a || !b) return !a && !b;
  return a.kind===b.kind && Number(a.hours)===Number(b.hours) && (a.start||'')===(b.start||'')
    && (a.shiftType||'')===(b.shiftType||'') && (a.bonusType||'none')===(b.bonusType||'none')
    && Number(a.customBonus||0)===Number(b.customBonus||0) && !!a.isOvertime===!!b.isOvertime;
}
/* 'day' | 'night' for any cell — fixed cells are classified by their differential key. */
function patternCellClass(cell){
  if(!cell) return null;
  if(cell.kind!=='fixed') return cell.kind;
  return /night|eve/.test(String(cell.shiftType||'')) ? 'night' : 'day';
}
/* The shift type the Add-Shift draft opens on. `active:false` means "don't offer me this in a
   picker" and NEVER "stop paying a shift already tagged with it" — nothing here re-prices a saved
   shift, and shiftGross/hourlyRate deliberately still pay a differential whose switch is off, so
   toggling one in Settings can never silently rewrite her logged pay history. This only chooses a
   starting chip. Prefers 'night' when it is on, so the default path is byte-identical to the old
   hard-coded 'night' (council #1 / wage-math-12: with Night switched off no chip was lit, yet the
   preview and the saved shift still carried the Night differential). */
function firstActiveShiftType(differentials){
  const d = differentials || {};
  const keys = Object.keys(d).filter(k => k!=='overtime' && d[k] && d[k].active);
  if(!keys.length) return 'base';
  return keys.indexOf('night')>=0 ? 'night' : keys[0];
}
function patternCellShiftType(cell, dateObj, differentials){
  if(!cell) return null;
  if(cell.kind==='fixed') return cell.shiftType;
  const isWeekend = dateObj.getDay()===0 || dateObj.getDay()===6;
  const active = k => !!(differentials && differentials[k] && differentials[k].active);
  if(cell.kind==='night'){
    if(isWeekend && active('weekend-eve')) return 'weekend-eve';
    return active('night') ? 'night' : 'base';
  }
  return (isWeekend && active('weekend-day')) ? 'weekend-day' : 'base';
}
/* The concrete shift a cell produces on a date (no id — callers assign one). */
function patternCellToShift(cell, dateObj, differentials){
  const st = patternCellShiftType(cell, dateObj, differentials);
  if(!st) return null;
  /* isOvertime was hard-coded false, so a rotation painted with a "Mandatory OT night" template
     priced ~31% under what the same template produces on the calendar — templates have carried
     the flag everywhere else since 2026-09-16 (council group-7 leftover). */
  const s = { shiftType:st, hours:Number(cell.hours), bonusType:cell.bonusType||'none', customBonus:Number(cell.customBonus||0), isOvertime:!!cell.isOvertime };
  if(cell.start) s.start = cell.start;
  return s;
}
/* Cell index a date falls on; the cycle extends both ways from the anchor. */
function patternIndexFor(pattern, dateObj){
  const a = parseISODate(pattern.anchor);
  const diff = Math.round((new Date(dateObj.getFullYear(),dateObj.getMonth(),dateObj.getDate()) - a)/86400000);
  const n = pattern.cells.length;
  return ((diff % n) + n) % n;
}

/* The per-paycheck tax model, factored out of App's calc() so the pattern lab prices a rotation
   with exactly the math the hero uses. `t` carries the same per-period inputs calc() reads. */
function computeNet(grossIn, t){
  /* Accepts either a plain gross (every existing call: all of it is taxable wages) or a
     {taxable, nonTaxable} split. The split is what a travel package actually looks like:
     Aya Healthcare, week of 2022-05-15, paid $3,096.00 of taxable wages and $1,442.00 of
     meals + housing stipend, and the stub's net is taxable - taxes + stipend to the cent.
     Withholding NEVER touches the non-taxable side; it passes straight through to net. */
  const isSplit = grossIn && typeof grossIn==='object' && !Array.isArray(grossIn);
  const taxable    = toCents(isSplit ? grossIn.taxable    : grossIn);
  const nonTaxable = toCents(isSplit ? grossIn.nonTaxable : 0);
  const pretax = toCents(t.pretaxDeductions), posttax = toCents(t.posttaxDeductions);
  // FICA (Social Security/Medicare) is levied on gross wages; pre-tax 401k/403b
  // deferrals only reduce income-tax wages. Keep the two bases separate.
  const ficaBase = taxable;
  const incomeTaxBase = Math.max(0, taxable - pretax);
  let fica = 0;
  if(t.ficaType==='standard') fica = roundCents(ficaBase*0.0765);
  else if(t.ficaType==='percent') fica = roundCents(ficaBase*((parseFloat(t.ficaPct)||0)/100));
  const fed = roundCents(incomeTaxBase*((Number(t.federalTaxRate)||0)/100));
  const st  = roundCents(incomeTaxBase*((Number(t.stateTaxRate)||0)/100));
  let cw = 0;
  (t.customWithholdings||[]).forEach(w=>{ cw += w.type==='percent'
    ? roundCents(incomeTaxBase*((parseFloat(w.amount)||0)/100))
    : toCents(parseFloat(w.amount)||0); });
  const ded = pretax+fica+fed+st+posttax+cw;
  const net = Math.max(0, taxable-ded) + nonTaxable;
  // Cap displayed flat pre/post at what gross can absorb so Breakdown rows still sum.
  const flatCapTotal = Math.max(0, taxable - (fica+fed+st+cw));
  const dispPre  = Math.min(pretax, flatCapTotal);
  const dispPost = Math.min(posttax, Math.max(0, flatCapTotal - dispPre));
  const total = taxable + nonTaxable;
  return {gross:fromCents(taxable), nonTaxable:fromCents(nonTaxable), total:fromCents(total),
    fica:fromCents(fica), fed:fromCents(fed), st:fromCents(st), cw:fromCents(cw),
    ded:fromCents(ded), net:fromCents(net), pre:fromCents(dispPre), post:fromCents(dispPost),
    pct: total>0 ? Math.round(net/total*100) : 0};
}

/* One pay period's paycheck: the hero figure and its Breakdown. Hoisted out of App's calc()
   (2026-10-07) so the MCP gateway prices a period with this exact function instead of a copy —
   App calls it with the same inputs it always read, and the body is calc()'s, statement for
   statement, including the dollar-side accumulation order. `dateKeys` are the period's
   YYYY-MM-DD keys; `job` is the active job from makeJob(). */
function periodPaycheck({shifts, dayEvents, dateKeys, baseRate, differentials, taxInputs, job}){
  let gross=0, hours=0;
  const periodKeys = new Set(dateKeys);
  Object.keys(shifts).forEach(k=>{
    if(!periodKeys.has(k)) return;
    (shifts[k]||[]).forEach(s=>{
      gross += shiftGross(baseRate, differentials[s.shiftType], s, job);
      hours += paidHoursOf(s, job);
    });
  });
  // PTO: hours × baseRate adds to gross like worked time (taxed normally), but skips
  // differentials/bonuses entirely — scoped to the active pay period same as shifts.
  Object.keys(dayEvents).forEach(k=>{
    if(!periodKeys.has(k)) return;
    (dayEvents[k]||[]).forEach(e=>{
      if(e.kind==='pto' && e.hours>0){ gross += e.hours*baseRate; hours += e.hours; }
    });
  });
  /* Overtime is a property of the work period: shiftGross has already paid every hour at its
     own rate, and this adds half the FLSA regular rate on the hours past the threshold. Hours
     the nurse flagged by hand are excluded inside overtimePremiumCents, so a figure she is
     already seeing cannot double. */
  const ot = overtimePremiumCents(job, shifts, dateKeys);
  gross += fromCents(ot.premiumCents);
  return {...computeNet(gross, taxInputs), hours, ot, otWorkPeriod:job.workPeriod};
}

/* Effective per-shift take-home ratio for live previews (Add-Shift, calendar cells, goal lines).
   Hoisted out of App 2026-10-07 for the same reason as periodPaycheck. Percent custom
   withholdings are a marginal rate exactly like fed/state and count here; flat-dollar ones are a
   per-paycheck amount, not a rate, so they stay out on purpose (council #8 / cross-surface-00). */
function keepRatioOf(t){
  const ficaForPreview = t.ficaType==='standard'?7.65:(t.ficaType==='percent'?(parseFloat(t.ficaPct)||0):0);
  const pctWithholdings = (t.customWithholdings||[]).reduce((a,w)=>
    a + (w && w.type==='percent' ? (parseFloat(w.amount)||0) : 0), 0);
  return Math.max(0, 1 - (t.federalTaxRate+t.stateTaxRate+ficaForPreview+pctWithholdings)/100);
}

/* Everything the lab shows about a pattern — the money AND the shape of the life it makes.
   Money is averaged over lcm(cycle,14) days so a cycle that doesn't divide a fortnight (the 8-day
   "4 on 4 off") still yields an honest per-paycheck figure. Runs are cyclic: the pattern repeats,
   so a stretch of shifts that wraps the cycle boundary counts as one run. */
function patternMetrics(pattern, baseRate, differentials, taxes){
  const cells = (pattern && pattern.cells) || [];
  const n = cells.length;
  const out = { n, shifts:0, hours:0, hoursPerWeek:0, nights:0, days:0, longestRun:0, longestBreak:0, flips:0,
    weekendsWorked:0, weekendsTotal:0, weekendEvery:null, alwaysOff:[], drifts:n%7!==0,
    periodGross:0, periodNet:0, periodHours:0, yearNet:0, mix:'none' };
  if(!n) return out;
  const on = cells.map(c=>!!c);
  out.shifts = on.filter(Boolean).length;
  cells.forEach(c=>{ if(!c) return; out.hours += Number(c.hours)||0; if(patternCellClass(c)==='night') out.nights++; else out.days++; });
  const run = want => { let best=0,cur=0; for(let i=0;i<2*n;i++){ if(on[i%n]===want){ cur++; if(cur>best) best=Math.min(cur,n); } else cur=0; } return best; };
  out.longestRun = run(true);
  out.longestBreak = run(false);
  // back-to-back day/night flips: consecutive WORKING days whose class differs (cyclic)
  if(n>1) for(let i=0;i<n;i++){ const a=cells[i], b=cells[(i+1)%n]; if(a && b && patternCellClass(a)!==patternCellClass(b)) out.flips++; }
  out.mix = out.nights && out.days ? 'mixed' : out.nights ? 'nights' : out.days ? 'days' : 'none';
  if(!out.drifts){
    const w = parseISODate(pattern.anchor).getDay();
    const worked = new Set();
    cells.forEach((c,i)=>{ if(c) worked.add((w+i)%7); });
    out.alwaysOff = [0,1,2,3,4,5,6].filter(d=>!worked.has(d));
  }
  // money + weekends over lcm(cycle, 14) days from the anchor (whole weeks, so every Saturday in
  // the span is a full weekend — its Sunday is cell (i+1)%n, inside the repeating cycle)
  const span = lcm(n, 14);
  const a = parseISODate(pattern.anchor);
  let gross=0, hours=0;
  for(let i=0;i<span;i++){
    const dt = new Date(a.getFullYear(), a.getMonth(), a.getDate()+i);
    if(dt.getDay()===6){ out.weekendsTotal++; if(cells[i%n] || cells[(i+1)%n]) out.weekendsWorked++; }
    const cell = cells[i%n];
    if(!cell) continue;
    const s = patternCellToShift(cell, dt, differentials);
    gross += shiftGross(baseRate, differentials[s.shiftType], s);
    hours += s.hours;
  }
  if(out.weekendsTotal){ const g=gcd(out.weekendsWorked,out.weekendsTotal); out.weekendEvery = [out.weekendsWorked/g, out.weekendsTotal/g]; }
  const periods = span/14;
  out.periodGross = gross/periods;
  out.periodHours = hours/periods;
  out.hoursPerWeek = hours*7/span;
  out.periodNet = computeNet(out.periodGross, taxes).net;
  out.yearNet = out.periodNet*26;
  return out;
}

/* Pure apply planner: which days get a shift, which are skipped because they already hold one
   (never clobbered unless `replace`). Feeds both the lab's "Adds N shifts" preview and the apply. */
function planPatternApply(pattern, shifts, differentials, opts){
  const start = parseISODate(opts.startISO);
  const total = Math.max(1, Math.round(opts.weeks||4))*7;
  const adds=[]; let skipped=0, replaced=0;
  for(let i=0;i<total;i++){
    const dt = new Date(start.getFullYear(),start.getMonth(),start.getDate()+i);
    const cell = pattern.cells[patternIndexFor(pattern, dt)];
    if(!cell) continue;
    const k = keyOfDate(dt);
    if((shifts[k]||[]).length){ if(!opts.replace){ skipped++; continue; } replaced++; }
    adds.push({k, shift:patternCellToShift(cell, dt, differentials)});
  }
  const endDt = new Date(start.getFullYear(),start.getMonth(),start.getDate()+total-1);
  return {adds, skipped, replaced, startKey:keyOfDate(start), endKey:keyOfDate(endDt)};
}

/* ---- region: personas ---- */
const PERSONA_IDS = ['healthcare','other'];
const WORK_STATUSES = ['ft','pt','prn'];
const UNION_ANSWERS = ['yes','no','unsure'];
const OB_SHIFT_LENGTHS = [8,10,12];
/* Healthcare IS today's defaults -- App's initial state, resetToDefaults and the example-rate
   path all read this object, and tests/core.test.mjs pins every value against a literal, so
   neither the preset nor the defaults can move without a red test. Taxes are user-level (see
   makeJob) and identical across presets; applyPersona never writes them. */
const PERSONA_PRESETS = {
  healthcare: {
    baseRate:65.15, federalTaxRate:12, stateTaxRate:2.5, pretaxDeductions:0, posttaxDeductions:0,
    ficaType:'standard', ficaPct:7.65, workPeriod:'40', otMethod:'regular-rate',
    mealBreakMins:DEFAULT_MEAL_MINS, mealBreakMode:'included', differentials:DIFF_DEFAULTS,
    sampleMix:'rotating', extras:['diffs','holiday'], cards:{nursegrid:true},
  },
  /* Illustrative starting amounts, inside the $0.35-$2.75/h range docs/pay-rule-patterns.md saw
     for non-nurse differentials. They cannot move this persona's first estimate (its sample is
     all day shifts) and the estimate banner says to sharpen them. */
  other: {
    baseRate:25, federalTaxRate:12, stateTaxRate:2.5, pretaxDeductions:0, posttaxDeductions:0,
    ficaType:'standard', ficaPct:7.65, workPeriod:'40', otMethod:'regular-rate',
    mealBreakMins:DEFAULT_MEAL_MINS, mealBreakMode:'included',
    differentials:{...DIFF_DEFAULTS,
      'night':       {...DIFF_DEFAULTS['night'],       amount:1.5, active:true},
      'weekday-eve': {...DIFF_DEFAULTS['weekday-eve'], amount:1,   active:true},
      'weekend-day': {...DIFF_DEFAULTS['weekend-day'], amount:1,   active:false},
      'weekend-eve': {...DIFF_DEFAULTS['weekend-eve'], amount:1.5, active:false}},
    sampleMix:'days', extras:['evenings','weekend','holiday'], cards:{nursegrid:false},
  },
};
const personaPreset = id => PERSONA_PRESETS[PERSONA_IDS.indexOf(id)>=0 ? id : 'healthcare'];
const DEFAULT_PRESET = PERSONA_PRESETS.healthcare;
/* Which differential keys each extras toggle on screen 6 flips. `active` only -- amounts stay
   whatever the preset or a stub set, and live in Settings. */
const OB_EXTRA_KEYS = {
  diffs:    ['night','weekend-day','weekend-eve'],
  evenings: ['weekday-eve','night'],
  weekend:  ['weekend-day','weekend-eve'],
  holiday:  ['holiday'],
};
/* Shifts per week that seed the first estimate. Full-time 12h is 3 a week = 72 h a period,
   not 80 (owner, 2026-10-10). Part-time is ~24 h a week; PRN one shift a week. */
const OB_SHIFTS_PER_WEEK = { ft:{8:5,10:4,12:3}, pt:{8:3,10:2,12:2}, prn:{8:1,10:1,12:1} };
/* The funnel's answers -> buildSampleShifts' opts. Nights and weekends are seeded only when the
   persona's mix rotates AND that extra is on: `active:false` never stops pricing a shift already
   tagged night, so seeding nights she said she doesn't get would price them anyway. */
function obSeedOpts(shiftLen, workStatus, sampleMix, extrasOn){
  const hours = OB_SHIFT_LENGTHS.indexOf(Number(shiftLen))>=0 ? Number(shiftLen) : 12;
  const st = WORK_STATUSES.indexOf(workStatus)>=0 ? workStatus : 'ft';
  const rotate = sampleMix==='rotating' && !!(extrasOn && extrasOn.diffs);
  return { hours, perWeek: OB_SHIFTS_PER_WEEK[st][hours], mix: rotate ? 'rotating' : 'days' };
}
/* Add a seeded fortnight to whatever she already has, never replacing a shift. The header meter
   and finish() both price through this, so the meter's figure is the hero's figure. */
function mergeSeed(prev, seed){
  const next = {...(prev||{})};
  Object.keys(seed||{}).forEach(k=>{ next[k] = (next[k]||[]).concat(seed[k]); });
  return next;
}
/* An extra reads as ON when every differential it governs is active. Derived from the
   differentials themselves rather than stored, so a stub that lit some of them is reflected. */
function obExtrasOn(differentials){
  const d = differentials || {};
  const out = {};
  Object.keys(OB_EXTRA_KEYS).forEach(x=>{ out[x] = OB_EXTRA_KEYS[x].every(k=>!!(d[k] && d[k].active)); });
  return out;
}
/* Annual salary -> the hourly rate the planner prices with, on the standard 2,080-hour year.
   An INPUT conversion, not a salaried pay model (that is primitive 4 in pay-rule-patterns.md,
   and wage-core): right for an 80-hour fortnight, ~10% low for a 72-hour one, which is why the
   pay screen prints the rate it will use before she continues. */
const SALARY_HOURS_PER_YEAR = 2080;
const salaryToHourly = annual => {
  const n = Number(annual);
  return (isFinite(n) && n > 0) ? Math.round(n / SALARY_HOURS_PER_YEAR * 100) / 100 : 0;
};

/* The funnel's analytics contract. Every ob_* event passes through obEventProps, which returns
   only whitelisted keys with enumerated values, or null -- and a null is never sent. Nothing she
   typed is ever a value: `pay` records HOW she answered, never the amount. */
const OB_SCREENS = ['landing','persona','shift','status','union','pay','extras'];
const OB_ANSWERS = {
  persona: PERSONA_IDS,
  shift: OB_SHIFT_LENGTHS.map(String),
  status: WORK_STATUSES,
  union: UNION_ANSWERS,
  pay: ['stub','hourly','salary','example'],
  x_diffs: ['on','off'], x_evenings: ['on','off'], x_weekend: ['on','off'], x_holiday: ['on','off'],
};
function obEventProps(name, props){
  const p = (props && typeof props==='object') ? props : {};
  if(name==='ob_view') return OB_SCREENS.indexOf(p.screen)>=0 ? {screen:p.screen} : null;
  if(name==='ob_back') return OB_SCREENS.indexOf(p.from)>=0 ? {from:p.from} : null;
  if(name==='ob_answer'){
    const allowed = Object.prototype.hasOwnProperty.call(OB_ANSWERS, p.q) ? OB_ANSWERS[p.q] : null;
    const a = (typeof p.a==='string' || typeof p.a==='number') ? String(p.a) : '';
    return (Array.isArray(allowed) && allowed.indexOf(a)>=0) ? {q:p.q, a} : null;
  }
  return null;
}

export {
  MAX_TEMPLATES,
  MAX_GOALS,
  todayISO,
  parseISODate,
  keyOfDate,
  periodStartOf,
  periodRangeLabel,
  DIFF_DEFAULTS,
  CUSTOM_DIFF_COLOR,
  PREV_DIFF_COLORS,
  migrateDiffColor,
  SAMPLE_PATTERN_ID,
  buildSampleShifts,
  BONUS,
  BONUS_LABEL,
  EVENT_KINDS,
  EVENT_KIND_META,
  MAX_DAY_EVENTS,
  MAX_NOTE_LEN,
  TIME_RE,
  ICS_UID_RE,
  ICS_IMPORT_MAX_EVENTS,
  ICS_IMPORT_PAST_DAYS,
  ICS_IMPORT_FUTURE_DAYS,
  ICS_IGNORED_MAX,
  ICS_EVENT_KIND,
  EARN_NUM_RE,
  EARN_CENT_TOLERANCE,
  parseEarningsRows,
  differentialsFromStub,
  PAYSTUB_NOT_A_DIFFERENTIAL,
  classifyPaystubRow,
  sanitizeData,
  fmt,
  fmt2,
  toCents,
  fromCents,
  roundCents,
  DEFAULT_JOB_ID,
  MAX_JOBS,
  WORK_PERIODS,
  OT_METHODS,
  PAY_FREQUENCIES,
  MEAL_MODES,
  DEFAULT_MEAL_MINS,
  makeJob,
  jobMap,
  straightTimeCents,
  workPeriodChunks,
  overtimePremiumCents,
  groupHoursByJob,
  paidHoursOf,
  hourlyRateCents,
  shiftGrossCents,
  hourlyRate,
  shiftGross,
  MAX_PATTERNS,
  PATTERN_MIN_CYCLE,
  PATTERN_MAX_CYCLE,
  PATTERN_KINDS,
  PATTERN_CYCLE_CHOICES,
  PATTERN_APPLY_WEEKS,
  DOW_SHORT,
  gcd,
  lcm,
  PATTERN_PRESETS,
  PATTERN_BRUSHES,
  presetCell,
  patternFromPreset,
  blankPattern,
  patternCellEq,
  patternCellClass,
  firstActiveShiftType,
  patternCellShiftType,
  patternCellToShift,
  patternIndexFor,
  computeNet,
  periodPaycheck,
  keepRatioOf,
  patternMetrics,
  planPatternApply,
  PERSONA_IDS,
  WORK_STATUSES,
  UNION_ANSWERS,
  OB_SHIFT_LENGTHS,
  PERSONA_PRESETS,
  personaPreset,
  DEFAULT_PRESET,
  OB_EXTRA_KEYS,
  OB_SHIFTS_PER_WEEK,
  obSeedOpts,
  mergeSeed,
  obExtrasOn,
  SALARY_HOURS_PER_YEAR,
  salaryToHourly,
  OB_SCREENS,
  OB_ANSWERS,
  obEventProps,
};
