#!/usr/bin/env node
/* Extract BadgeBudget's pure domain core from index.html into an importable ES module.

   index.html stays the single source of truth and the deployed artifact stays one file with no
   build step (CLAUDE.md → Architecture). Instead of moving the wage math OUT of the app and
   building it back in, the math is marked in place:

       /* @core:begin <name> *\/   …pure code…   /* @core:end *\/

   and this script slices the marked regions, in file order, into
   supabase/functions/_shared/badgebudget-core.mjs with every top-level declaration exported.
   Node tests import that file, and so will the MCP gateway (an Edge Function; `_shared/` is
   Supabase's convention for code shared between functions). One copy of the math, two callers.

   The generated file is committed. `--check` regenerates in memory and fails if the committed
   copy differs, so an edit to a marked region that forgets to re-run this script is a red CI
   run, not a gateway that quietly prices shifts with last month's math.

   It also refuses to emit a module that reaches outside itself: every free identifier in the
   marked code must be a JS built-in from ALLOWED_GLOBALS. A marked region that starts calling
   `window`, `localStorage` or `supabase` fails here rather than at the first gateway request.

   Usage:  node scripts/extract_core.mjs           # write the module
           node scripts/extract_core.mjs --check   # exit 1 if the committed module is stale
*/
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const SRC = join(ROOT, 'index.html');
export const OUT = join(ROOT, 'supabase/functions/_shared/badgebudget-core.mjs');

const ALLOWED_GLOBALS = new Set(['Math','Number','String','Object','Array','Date','JSON','Set',
  'Map','isNaN','isFinite','parseFloat','parseInt','RegExp','Boolean','Infinity','NaN',
  'undefined','Error','TypeError','RangeError','Intl','Symbol','TextEncoder']);

const BEGIN = /\/\* @core:begin ([a-z0-9-]+) \*\//g;
const END = '/* @core:end */';

function loadBabel(){
  const require = createRequire(import.meta.url);
  try { return require('@babel/standalone'); }
  catch(_){ throw new Error('no Babel available — run: npm install --no-save @babel/standalone@7.24.7'); }
}

/* Returns {regions:[{name, code}], code, exports, unresolved}. Pure: reads nothing but `html`. */
export function extractCore(html, Babel = loadBabel()){
  const regions = [];
  BEGIN.lastIndex = 0;
  let m;
  while((m = BEGIN.exec(html))){
    const start = m.index + m[0].length;
    const stop = html.indexOf(END, start);
    if(stop < 0) throw new Error(`@core:begin ${m[1]} has no matching @core:end`);
    const nested = html.slice(start, stop).search(/\/\* @core:begin /);
    if(nested >= 0) throw new Error(`@core:begin ${m[1]} is not closed before the next @core:begin`);
    regions.push({ name: m[1], code: html.slice(start, stop).replace(/^\n/, '').replace(/\s+$/, '') });
    BEGIN.lastIndex = stop + END.length;
  }
  if(!regions.length) throw new Error('no @core regions found in index.html');
  const names = regions.map(r => r.name);
  const dup = names.find((n, i) => names.indexOf(n) !== i);
  if(dup) throw new Error(`duplicate @core region name: ${dup}`);

  const code = regions.map(r => `/* ---- region: ${r.name} ---- */\n${r.code}`).join('\n\n');
  let exports = [], unresolved = [];
  Babel.transform(code, { sourceType: 'module', plugins: [() => ({ visitor: { Program(p){
    exports = Object.keys(p.scope.bindings);
    unresolved = Object.keys(p.scope.globals).filter(g => !ALLOWED_GLOBALS.has(g));
  }}})]});
  return { regions, code, exports, unresolved };
}

export function renderModule({ code, exports }){
  return [
    '// GENERATED by scripts/extract_core.mjs from the @core regions of index.html — DO NOT EDIT.',
    '// Edit index.html, then run: node scripts/extract_core.mjs',
    '// CI fails if this file is out of sync (scripts/check_build.mjs).',
    '',
    code,
    '',
    `export {\n${exports.map(e => `  ${e},`).join('\n')}\n};`,
    '',
  ].join('\n');
}

export function buildCore(html = readFileSync(SRC, 'utf8')){
  const ex = extractCore(html);
  if(ex.unresolved.length)
    throw new Error(`@core regions reference identifiers outside the core: ${ex.unresolved.join(', ')}`);
  return { ...ex, module: renderModule(ex) };
}

if(process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]){
  const check = process.argv.includes('--check');
  try {
    const { module, regions, exports } = buildCore();
    if(check){
      const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
      if(cur !== module){
        console.error('core module is stale — run: node scripts/extract_core.mjs');
        process.exit(1);
      }
      console.log(`core module in sync (${regions.length} regions, ${exports.length} exports)`);
    } else {
      mkdirSync(dirname(OUT), { recursive: true });
      writeFileSync(OUT, module);
      console.log(`wrote ${OUT.slice(ROOT.length + 1)} (${regions.length} regions, ${exports.length} exports)`);
    }
  } catch(e){
    console.error(String(e.message || e));
    process.exit(1);
  }
}
