#!/usr/bin/env node
/*
 * groom_seed.mjs — Phase 1 of the Reddit-insights pipeline (see docs/reddit-persona-pipeline.md).
 *
 * Reads the seed corpus (docs/reddit_seed.json) and the KNOWN corpus (CLAUDE.md + BACKLOG.md),
 * validates the seed schema, dedupes each insight against what's already documented/queued, and
 * emits SOURCE-TAGGED, priority-proposed candidate backlog items for the themes not already
 * covered. This is the mechanical half of the GROOM step; the nightly agent applies judgment on
 * top (final priority, wording, whether a "covered" area still hides a gap).
 *
 * Usage:
 *   node scripts/groom_seed.mjs            # dry-run report (default)
 *   node scripts/groom_seed.mjs --json     # machine-readable JSON for the groom agent
 *   node scripts/groom_seed.mjs --apply    # write/replace an idempotent managed block in BACKLOG.md
 *
 * Safety: --apply only ever touches a delimited managed block; it never rewrites hand-authored
 * backlog content, and re-running replaces (never duplicates) the block. index.html is never touched.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SEED_PATH = join(ROOT, 'docs', 'reddit_seed.json');
const BACKLOG_PATH = join(ROOT, 'BACKLOG.md');
const CLAUDEMD_PATH = join(ROOT, 'CLAUDE.md');

const PRIORITY_MAP = { loud: 'P1', recurring: 'P2', occasional: 'P3', 'one-off': 'P3' };
const VALID_SIGNAL = new Set(Object.keys(PRIORITY_MAP));
const VALID_SOURCE = new Set(['seed', 'reddit-live']);
const COVER_THRESHOLD = 2; // distinct keyword hits in the known corpus => treat as already-covered
const BLOCK_START = '<!-- GROOM_SEED:BEGIN (managed by scripts/groom_seed.mjs — do not edit by hand) -->';
const BLOCK_END = '<!-- GROOM_SEED:END -->';

const norm = s => String(s).toLowerCase().replace(/[^a-z0-9]+/g, ' ').replace(/\s+/g, ' ').trim();

// Remove our own managed block from a BACKLOG string before using it as the "known" corpus —
// otherwise the candidate themes we wrote last run would match themselves and erode to nothing.
export function stripManagedBlock(text) {
  const s = text.indexOf(BLOCK_START);
  const e = text.indexOf(BLOCK_END);
  if (s !== -1 && e !== -1 && e > s) return text.slice(0, s) + text.slice(e + BLOCK_END.length);
  return text;
}

export function validateInsight(x, i) {
  const errs = [];
  const req = ['id', 'theme', 'category', 'signal', 'paraphrase', 'mapped_feature', 'keywords', 'confidence', 'source'];
  for (const k of req) if (!(k in x)) errs.push(`[${i}] missing "${k}"`);
  if (x.signal && !VALID_SIGNAL.has(x.signal)) errs.push(`[${i}:${x.id}] bad signal "${x.signal}"`);
  if (x.source && !VALID_SOURCE.has(x.source)) errs.push(`[${i}:${x.id}] bad source "${x.source}"`);
  if (x.keywords && (!Array.isArray(x.keywords) || x.keywords.length === 0)) errs.push(`[${i}:${x.id}] keywords must be a non-empty array`);
  if (typeof x.id === 'string' && !/^[a-z0-9-]+$/.test(x.id)) errs.push(`[${i}] id "${x.id}" must be kebab-case`);
  return errs;
}

export function analyze(seed, knownText) {
  const known = ' ' + norm(knownText) + ' ';
  return seed.insights.map(x => {
    // match on distinctive keywords only (>=4 normalized chars) to avoid noisy short-token hits
    // like "ot" matching "not"/"cannot"; substring match after normalization (hyphens->spaces).
    const matched = [...new Set(x.keywords)].filter(k => { const n = norm(k); return n.length >= 4 && known.includes(n); });
    const covered = matched.length >= COVER_THRESHOLD;
    return {
      id: x.id,
      category: x.category,
      signal: x.signal,
      mapped_feature: x.mapped_feature,
      priority: PRIORITY_MAP[x.signal] || 'P3',
      status: covered ? 'covered' : 'candidate',
      matched,
      theme: x.theme,
      paraphrase: x.paraphrase,
      source: x.source,
    };
  });
}

function backlogLine(r) {
  // one source-tagged, priority-proposed backlog bullet
  return `- [ ] **${r.theme}** (${r.priority} · source:reddit-${r.source} · ${r.category}) — ${r.paraphrase} `
    + `Maps to \`${r.mapped_feature}\`. Auto-surfaced from the Reddit seed corpus; groom to confirm priority/scope before build.`;
}

export function renderBlock(candidates) {
  const byPri = { P1: [], P2: [], P3: [] };
  for (const c of candidates) (byPri[c.priority] || byPri.P3).push(c);
  const lines = [BLOCK_START,
    '### Reddit-seeded candidates (auto — review before building)',
    '_Generated by `scripts/groom_seed.mjs` from `docs/reddit_seed.json`. Deduped against CLAUDE.md + BACKLOG.md. '
    + 'Promote an item into the priority queues above (and delete it here) once a human/groom confirms it; '
    + 'these still pass the normal safety gate before any deploy._', ''];
  for (const p of ['P1', 'P2', 'P3']) {
    if (!byPri[p].length) continue;
    lines.push(`**${p}**`);
    for (const c of byPri[p]) lines.push(backlogLine(c));
    lines.push('');
  }
  lines.push(BLOCK_END);
  return lines.join('\n');
}

export function applyBlock(backlogText, blockText) {
  const s = backlogText.indexOf(BLOCK_START);
  const e = backlogText.indexOf(BLOCK_END);
  if (s !== -1 && e !== -1 && e > s) {
    // replace existing managed block in place (idempotent)
    return backlogText.slice(0, s) + blockText + backlogText.slice(e + BLOCK_END.length);
  }
  // insert before the "## Done (log)" section so candidates sit with the queue, else append
  const doneIdx = backlogText.indexOf('## Done (log)');
  if (doneIdx !== -1) return backlogText.slice(0, doneIdx) + blockText + '\n\n' + backlogText.slice(doneIdx);
  return backlogText.replace(/\s*$/, '') + '\n\n' + blockText + '\n';
}

function main() {
  const args = new Set(process.argv.slice(2));
  const seed = JSON.parse(readFileSync(SEED_PATH, 'utf8'));

  const schemaErrs = seed.insights.flatMap(validateInsight);
  if (schemaErrs.length) {
    console.error('SEED SCHEMA ERRORS:\n' + schemaErrs.join('\n'));
    process.exit(1);
  }

  const knownText = readFileSync(CLAUDEMD_PATH, 'utf8') + '\n' + stripManagedBlock(readFileSync(BACKLOG_PATH, 'utf8'));
  const results = analyze(seed, knownText);
  const candidates = results.filter(r => r.status === 'candidate');
  const covered = results.filter(r => r.status === 'covered');

  if (args.has('--json')) {
    console.log(JSON.stringify({ candidates, covered }, null, 2));
    return;
  }

  if (args.has('--apply')) {
    const backlog = readFileSync(BACKLOG_PATH, 'utf8');
    const next = applyBlock(backlog, renderBlock(candidates));
    writeFileSync(BACKLOG_PATH, next);
    console.log(`Applied ${candidates.length} candidate(s) to BACKLOG.md managed block.`);
    return;
  }

  // default: human-readable dry-run report
  console.log(`Seed corpus: ${seed.insights.length} insights · schema OK`);
  console.log(`Deduped against CLAUDE.md + BACKLOG.md → ${candidates.length} candidate(s), ${covered.length} already covered.\n`);
  console.log('COVERED (skip — already documented/shipped/queued):');
  for (const r of covered) console.log(`  · ${r.id} [${r.mapped_feature}] matched: ${r.matched.join(', ')}`);
  console.log('\nCANDIDATES (source-tagged, priority-proposed):');
  for (const p of ['P1', 'P2', 'P3']) {
    const list = candidates.filter(c => c.priority === p);
    if (!list.length) continue;
    console.log(`  ${p}:`);
    for (const c of list) console.log(`    - ${c.id} [${c.category}] — ${c.theme}`);
  }
  console.log('\nRun with --apply to write these into the BACKLOG.md managed block, or --json for the groom agent.');
}

// only run main when invoked directly (keeps analyze() importable by the test without side effects)
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
